### ISSUE TITLE
Add timeout to RotateToAngle and MoveDistance commands

### ISSUE THREAD

**Issue by MatthewSpofford** [FRC4048/FRC2018_Java#69]

**Comment by batchen1** [comment]
Added a timeout to DriveDistance() decided not to add timeout to RotateAngle().
**Still need to change the 4 autonomous switch commands** to move 3 inches more, just to make sure we get very close to the switch.

**Comment by batchen1** [comment]
Added 3 inches to AutoSwitchLLGroup, RRGroup, MLGroup, MRGroup.
