### ISSUE TITLE
Optimize GetCubeGroupCommand to improve performance

### ISSUE THREAD

**Issue by MatthewSpofford** [FRC4048/FRC2018_Java#72]

**Comment by batchen1** [comment]
// 1 - close the intake arms		
		// 2 - lower the intake		
		// 3 - move arm to exchange position
		// 4 - level the claw
		// 5 - start intake until cube is in
		// 6 - open claw 
		// 7 - move arm to the right angle for pickup
		// 8 - retract arm 
		// 9 - open the intake arms
		// 10 - extension until hits cube
		// 11 - close gripper
		// 12 - lift arm to safe position
		// 13 - open intake arms
		// 14 - lift intake 
		
		
1+2 + wfc
3+4+5 + wfc
6+7+8 + wfc
9+10 + wfc
11
12
13+14
